datagrid:
    physicalstore-accounts-grid:
        pageTitle: demacmedia_physicalstore.accounts.entity_plural.label
        source:
            type: orm
            query:
                select:
                    - physicalstore_accounts.id
                    - physicalstore_accounts.custno
                    - physicalstore_accounts.contact
                    - physicalstore_accounts.city
                    - physicalstore_accounts.country
                    - physicalstore_accounts.phone
                    - physicalstore_accounts.salesrep
                    - physicalstore_accounts.updated
                    - physicalstore_accounts.created
                from:
                    - { table: DemacMediaPhysicalStoreBundle:OroPhysicalStoreAccounts, alias: physicalstore_accounts }
        columns:
            id:
                label: demacmedia_physicalstore.accounts.id.label
            custno:
                label: demacmedia_physicalstore.accounts.custno.label
            contact:
                label: demacmedia_physicalstore.accounts.contact.label
            city:
                label: demacmedia_physicalstore.accounts.city.label
            phone:
                label: demacmedia_physicalstore.accounts.phone.label
            salesrep:
                label: demacmedia_physicalstore.accounts.salesrep.label
            updated:
                label: demacmedia_physicalstore.accounts.updated.label
                frontend_type:    datetime

        sorters:
            columns:
                city:
                    data_name: physicalstore_accounts.city
                contact:
                    data_name: physicalstore_accounts.contact
                updated:
                    data_name: physicalstore_accounts.updated
            default:
                id: DESC

        properties:
            id: ~
            view_link:
                type:       url
                route:      demacmedia_physicalstore_accounts_view
                params:     [ custno ]

        actions:
            view:
                type:         navigate
                label:        oro.grid.action.view
                link:         view_link
                icon:         eye-open
                rowAction:    true

        filters:
            columns:
                custno:
                    type: string
                    data_name: physicalstore_accounts.custno
                contact:
                    type: string
                    data_name: physicalstore_accounts.contact
                city:
                    type: string
                    data_name: physicalstore_accounts.city
                phone:
                    type: string
                    data_name: physicalstore_accounts.phone
                salesrep:
                    type: string
                    data_name: physicalstore_accounts.salesrep
                updated:
                    type: datetime
                    data_name: physicalstore_accounts.updated


    # ORDERS FOR SPECIFIC ORDER
    ############################################################
    physicalstore-orders-specific-grid:
        pageTitle: demacmedia_physicalstore.orders.entity.label
        source:
            type: orm
            query:
                select:
                    - physicalstore_orders.id
                    - physicalstore_orders.invno
                    - physicalstore_orders.custno
                    - physicalstore_orders.invdate
                    - physicalstore_orders.shipvia
                    - physicalstore_orders.updated
                    - physicalstore_orders.invamt
                    - physicalstore_orders.salesrep
                    - physicalstore_orders.status
                    - physicalstore_orders.created
                from:
                    - { table: DemacMediaPhysicalStoreBundle:OroPhysicalStoreOrders, alias: physicalstore_orders }
                where:
                    and:
                        - physicalstore_orders.custno = :custno_code
            bind_parameters:
                custno_code: custno

        columns:
            id:
                label: demacmedia_physicalstore.orders.oroid.label
            invamt:
                label: demacmedia_physicalstore.orders.invamt.label
                frontend_type: currency
            invno:
                label: demacmedia_physicalstore.orders.invno.label
            custno:
                label: demacmedia_physicalstore.orders.custno.label
            invdate:
                label: demacmedia_physicalstore.orders.invdate.label
                frontend_type: date
            shipvia:
                label: demacmedia_physicalstore.orders.shipvia.label
            salesrep:
                label: demacmedia_physicalstore.orders.salesrep.label
            status:
                label: demacmedia_physicalstore.orders.status.label
            updated:
                label: demacmedia_physicalstore.orders.updated.label
                frontend_type: datetime

        sorters:
            columns:
                updated:
                    data_name: physicalstore_orders.updated
                custno:
                    data_name: physicalstore_orders.custno
            default:
                id: DESC

        properties:
            id: ~
            view_link:
                type:       url
                route:      demacmedia_physicalstore_orders_view
                params:     [ invno ]

        actions:
            view:
                type:         navigate
                label:        oro.grid.action.view
                link:         view_link
                icon:         eye-open
                rowAction:    true

        filters:
            columns:
                invno:
                    type: string
                    data_name: physicalstore_orders.invno
                invamt:
                    type: currency
                    data_name: physicalstore_orders.invamt
                shipvia:
                    type: string
                    data_name: physicalstore_orders.shipvia
                status:
                    type: string
                    data_name: physicalstore_orders.status
                salesrep:
                    type: string
                    data_name: physicalstore_orders.salesrep
                updated:
                    type: datetime
                    data_name: physicalstore_orders.updated


    # ORDERS and ACCOUNTS
    ############################################################
    physicalstore-orders-grid:
        pageTitle: demacmedia_physicalstore.orders.entity_plural.label
        source:
            type: orm
            query:
                select:
                    - physicalstore_orders.id
                    - physicalstore_orders.invno
                    - physicalstore_orders.custno
                    - physicalstore_orders.dateord
                    - physicalstore_orders.shipvia
                    - physicalstore_orders.invamt
                    - physicalstore_accounts.contact
                    - physicalstore_orders.salesrep
                    - physicalstore_orders.status
                    - physicalstore_orders.updated
                    - physicalstore_orders.created
                    - physicalstore_orders.shipcontact
                    - physicalstore_orders.shipcity
                    - physicalstore_orders.vendorno
                from:
                    - { table: DemacMediaPhysicalStoreBundle:OroPhysicalStoreOrders, alias: physicalstore_orders }
                join:
                    left:
                        - { join: DemacMediaPhysicalStoreBundle:OroPhysicalStoreAccounts, alias: physicalstore_accounts, conditionType: WITH, condition: 'physicalstore_accounts.custno = physicalstore_orders.custno' }
        columns:
            invno:
                label: demacmedia_physicalstore.orders.invno.label
            contact:
                label: demacmedia_physicalstore.accounts.contact.label
            shipcontact:
                label: demacmedia_physicalstore.orders.shipcontact.label
            dateord:
                label: demacmedia_physicalstore.orders.dateord.label
                frontend_type: date
            shipvia:
                label: demacmedia_physicalstore.orders.shipvia.label
            shipcity:
                label: demacmedia_physicalstore.orders.shipcity.label
            vendorno:
                label: demacmedia_physicalstore.orders.vendorno.label
            invamt:
                label: demacmedia_physicalstore.orders.invamt.label
                frontend_type: currency
            salesrep:
                label: demacmedia_physicalstore.orders.salesrep.label
            status:
                label: demacmedia_physicalstore.orders.status.label

        sorters:
            columns:
                dateord:
                    data_name: physicalstore_orders.dateord
                contact:
                    data_name: physicalstore_accounts.contact
            default:
                id: DESC

        properties:
            id: ~
            view_link:
                type:       url
                route:      demacmedia_physicalstore_orders_view
                params:     [ invno ]

        actions:
            view:
                type:         navigate
                label:        oro.grid.action.view
                link:         view_link
                icon:         eye-open
                rowAction:    true

        filters:
            columns:
                invno:
                    type: string
                    data_name: physicalstore_orders.invno
                contact:
                    type: string
                    data_name: physicalstore_accounts.contact
                shipcontact:
                    type: string
                    data_name: physicalstore_accounts.shipcontact
                shipvia:
                    type: string
                    data_name: physicalstore_orders.shipvia
                dateord:
                    type: datetime
                    data_name: physicalstore_orders.dateord
                salesrep:
                    type: string
                    data_name: physicalstore_orders.salesrep
                shipcity:
                    type: string
                    data_name: physicalstore_orders.shipcity
                vendorno:
                    type: string
                    data_name: physicalstore_orders.vendorno
                status:
                    type: string
                    data_name: physicalstore_orders.status


    physicalstore-order-items-grid:
        pageTitle: demacmedia_physicalstore.orderitems.entity_plural.label
        source:
            type: orm
            query:
                select:
                    - physicalstore_order_items.id
                    - physicalstore_order_items.invno
                    - physicalstore_order_items.custno
                    - physicalstore_order_items.item
                    - physicalstore_order_items.descrip
                    - physicalstore_order_items.taxrate
                    - physicalstore_order_items.cost
                    - physicalstore_order_items.qtyord
                    - physicalstore_order_items.price
                    - physicalstore_order_items.invdate
                    - physicalstore_order_items.ponum
                    - physicalstore_order_items.updated
                    - physicalstore_order_items.created
                from:
                    - { table: DemacMediaPhysicalStoreBundle:OroPhysicalStoreOrderItems, alias: physicalstore_order_items }
                where:
                    and:
                        - physicalstore_order_items.invno = :invno_code
            bind_parameters:
                invno_code: invno

        columns:
            id:
                label: demacmedia_physicalstore.order_items.oroid.label
            invno:
                label: demacmedia_physicalstore.order_items.invno.label
            item:
                label: demacmedia_physicalstore.order_items.item.label
            descrip:
                label: demacmedia_physicalstore.order_items.descrip.label
            cost:
                label: demacmedia_physicalstore.order_items.cost.label
                frontend_type: currency
            price:
                label: demacmedia_physicalstore.order_items.price.label
                frontend_type: currency
            qtyord:
                label: demacmedia_physicalstore.order_items.qtyord.label
            invdate:
                label: demacmedia_physicalstore.order_items.invdate.label
                frontend_type: date
            ponum:
                label: demacmedia_physicalstore.order_items.ponum.label
            updated:
                label: demacmedia_physicalstore.order_items.updated.label
                frontend_type: datetime

        sorters:
            columns:
                updated:
                    data_name: physicalstore_order_items.updated
            default:
                id: DESC

        filters:
            columns:
                item:
                    type: string
                    data_name: physicalstore_order_items.item
                descrip:
                    type: string
                    data_name: physicalstore_order_items.descrip
                updated:
                    type: datetime
                    data_name: physicalstore_order_items.updated
