parameters:
    oro_physicalstore_accounts.importexport.template_fixture.user.class:    Oro\Bundle\PhysicalStoreBundle\ImportExport\TemplateFixture\AccountsFixture

services:
    oro_physicalstore_accounts.importexport.data_converter:
        parent: oro_importexport.data_converter.configurable

    oro_physicalstore_accounts.importexport.template_fixture.data_converter:
        parent: oro_importexport.data_converter.template_fixture.configurable

    # Export processor
    oro_physicalstore_accounts.importexport.processor.export:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@oro_physicalstore_accounts.importexport.data_converter]]
        tags:
            - { name: oro_importexport.processor, type: export, entity: %oro_physicalstore_accounts.entity.class%, alias: oro_physicalstore_accounts }

    oro_physicalstore_accounts.importexport.processor.export_template:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@oro_physicalstore_accounts.importexport.template_fixture.data_converter]]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: %oro_physicalstore_accounts.entity.class%, alias: oro_physicalstore_accounts }

    oro_physicalstore_accounts.importexport.template_fixture.user:
        class: %oro_physicalstore_accounts.importexport.template_fixture.user.class%
        tags:
            - { name: oro_importexport.template_fixture }