oro_menu_config:
   items:
       physicalstore_tab:
           label: 'In-store'
           uri: '#'

       shortcut_accounts_item:
           label: 'Accounts'
           route: demacmedia_physicalstore_accounts

       shortcut_orders_item:
           label: 'Orders'
           route: demacmedia_physicalstore_orders
 
   tree:
       application_menu:
           children:
               physicalstore_tab:
                   children:
                       shortcut_accounts_item: ~
                       shortcut_orders_item: ~

oro_titles:
    demacmedia_physicalstore_accounts:  ~
    demacmedia_physicalstore_orders:    ~
