DemacMedia\Bundle\PhysicalStoreBundle\Entity\OroPhysicalStoreAccounts:
    alias: demacmedia_ps_accounts
    label: demacmedia_physicalstore.accounts.entity.label
    search_template: 'DemacMediaPhysicalStoreBundle:Search:result.html.twig'
    route:
        name: demacmedia_physicalstore_accounts_view
        parameters:
            custno: custno
    title_fields: [name]
    fields:
        -
            name: contact
            target_type: text
        -
            name: company
            target_type: text
        -
            name: custno
            target_type: text
